spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/INV-sec-DEV
    driverClassName: org.postgresql.Driver
    username: piotrek
    password: 248862
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days